title: "Science Summaries"
description: "Daily science summaries on physics, data science, and complexity."
baseurl: "" # Leave blank for GitHub Pages
url: "https://davismwhaley.github.io"

# Author Info
author:
  name: "Davis Whaley"
  email: "your@email.com"

# Theme Settings
theme: minima # <-- Use the standard minima theme
# remote_theme: "mmistakes/minimal-mistakes@4.24.0" # <-- This line should be removed or commented out
# minimal_mistakes_skin: "default" # <-- This line is specific to minimal-mistakes and should be removed or commented out

# Pagination
paginate: 12
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag


