title: My Science Summaries
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A site for bite-sized summaries of science papers.
baseurl: "" # leave empty for GitHub Pages user sites
url: "https://davismwhaley.github.io" # the base URL of your site
theme: minima

