title: "Science Summaries"
description: "Daily science summaries on physics, data science, and complexity."
baseurl: "" # Leave blank for GitHub Pages
url: "https://davismwhaley.github.io"

# Author Info
author:
  name: "Davis Whaley"
  email: "your@email.com"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Try specifying a version
minimal_mistakes_skin: "default"

# Pagination
paginate: 12
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag


